name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  suite:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.3']

    name: 'PHP ${{ matrix.php-versions }} test suite'
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: composer test
